# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mteval',
                'doc_host': 'https://polyglottech.github.io',
                'git_url': 'https://github.com/polyglottech/mteval',
                'lib_path': 'mteval'},
  'syms': {'mteval.core': {'mteval.core.foo': ('core.html#foo', 'mteval/core.py')}}}