# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_awsmt.ipynb.

# %% auto 0
__all__ = ['awstranslate']

# %% ../nbs/06_awsmt.ipynb 8
import os
import boto3
import time
from pathlib import Path

class awstranslate:
    """Class to get translations from the Amazon Web Service Translate API"""
    def __init__(self):
        """Constructor of awstranslate class"""
        # Authentication via environment variables
        self._translate_client = boto3.client(service_name='translate', use_ssl=True)


    def translate_text(self,sourcelang, targetlang, text):
        """Function to translate text into the target language"""
        result = self._translate_client.translate_text(Text=text, SourceLanguageCode=sourcelang, TargetLanguageCode=targetlang)
        
        return result.get('TranslatedText')

