# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_util.ipynb.

# %% auto 0
__all__ = ['util']

# %% ../nbs/08_util.ipynb 8
class util:
    """Class with several utility functions"""
    def __init__(self):
        """Constructor of util class"""
        self._singletrans = str.maketrans("‚‘’‹›","\'\'\'\'\'")
        self._doubletrans = str.maketrans("„“”«»","\"\"\"\"\"")

    def normalize_quotes(self,text):
        """Function to normalize various Unicode single quotes into U+0027 (Apostrophe) and double quotes into U+0022 (Quotation Mark)"""
        norm = text.translate(self._doubletrans)
        norm = norm.translate(self._singletrans)

        return norm
